export const strings = {
  home:
    "This site is a simple tool for coping those hard-to-type characters to your clipboard in order to use it in your documents or projects. Just click and paste!",
  arrows: "Teum",
  blocks: "",
  boxes: "",
  currency: "",
  cyrillic: "",
  "cyrillic-sup": "",
  diacritical: "",
  dingbats: "",
  latin: "",
  extended: "",
  extended2: "",
  "latin-mod": "",
  greek: "",
  hebrew: "",
  math: "",
  punctuation: "",
  shapes: "",
  spaces: "",
  symbols: "",
  typography: "",
  yellow: "",
};
